services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/mounir-ai/n8n-on-render
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "motdepassefort"
      - key: N8N_HOST
        value: n8n-mirfad.onrender.com
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-mirfad.onrender.com
